"""create table

Revision ID: 1684ec10f284
Revises: b10669fe19a9
Create Date: 2024-03-23 22:02:52.000822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1684ec10f284'
down_revision: Union[str, None] = 'b10669fe19a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_date', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'order_id')
    op.drop_column('orders', 'order_date')
    # ### end Alembic commands ###
